### ISSUE TITLE
category-export uses deprecated commands

### ISSUE THREAD

**Issue by mauritslamers** [tmuras/moosh#108]
I have moosh installed through the Ubuntu PPA. 

When I use moosh category-export on a Moodle 2.8 instance, I get the following message (above the exported XML):

```
++ Function get_course_category_tree() is deprecated, please use course renderer or coursecat class, see function phpdocs for more info ++
* line 3108 of /lib/deprecatedlib.php: call to debugging()
* line 35 of /usr/share/moosh/Moosh/Command/Moodle23/Category/CategoryExport.php: call to get_course_category_tree()
* line 274 of /usr/bin/moosh: call to Moosh\Command\Moodle23\Category\CategoryExport->execute()
++ context_instance_preload_sql() is deprecated, please use context_helper::get_preload_record_columns_sql() instead. ++
* line 4187 of /lib/deprecatedlib.php: call to debugging()
* line 3145 of /lib/deprecatedlib.php: call to context_instance_preload_sql()
* line 35 of /usr/share/moosh/Moosh/Command/Moodle23/Category/CategoryExport.php: call to get_course_category_tree()
* line 274 of /usr/bin/moosh: call to Moosh\Command\Moodle23\Category\CategoryExport->execute()
```

**Comment by dkns** [comment]
Hi, this is already fixed: https://github.com/tmuras/moosh/issues/89 

When did you install moosh?

**Comment by mauritslamers** [comment]
Today... Could it be that this fix is only included for Ubuntu versions later than 12.04?

**Comment by dkns** [comment]
Can you try installing this one after removing previously installed version? http://ppa.launchpad.net/zabuch/ppa/ubuntu/pool/main/m/moosh/moosh_0.19-1_all.deb

**Comment by mauritslamers** [comment]
I purged the existing one, then downloaded and installed this package with dpkg -i, I still have the issue.

**Comment by tmuras** [comment]
It should work fine with latest moosh (0.19) and Moodle 2.8.
It may be that on ubuntu 12 you're getting an old version of the package, I've switched to Ubuntu 14 dome time ago.

Can you confirm your moosh version, type just:
moosh
and check version reported at the top, e.g.:

tomasz@mm ~ % moosh
moosh version 0.19
No command provided, possible commands:

Also check your package version with
dpkg -l moosh

**Comment by mauritslamers** [comment]
```
# moosh
moosh version 0.19
No commands provided...
```

and

```
dpkg -l moosh
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-========================================================================
ii  moosh                             0.19-1                all                   Commandline utility helper for Moodle
```

I double checked the Linux version, and it turns out I am running ubuntu 14.04.3 LTS. Excuses for the wrong information.

**Comment by dkns** [comment]
@tmuras I installed 0.19 from deb package and tried running category-export on fresh 3.0 installation of moodle and got this error:
```
Default exception handler: Coding error detected, it must be fixed by a programmer: Function get_course_category_tree() is removed, please use course renderer or coursecat class,
            see function phpdocs for more info Debug: 
Error code: codingerror
* line 1630 of /lib/deprecatedlib.php: coding_exception thrown
* line 35 of /usr/share/moosh/Moosh/Command/Moodle23/Category/CategoryExport.php: call to get_course_category_tree()
* line 274 of /usr/bin/moosh: call to Moosh\Command\Moodle23\Category\CategoryExport->execute()

!!! Coding error detected, it must be fixed by a programmer: Function get_course_category_tree() is removed, please use course renderer or coursecat class,
            see function phpdocs for more info !!!
```

So it seems like there is something wrong with .deb package?

**Comment by mauritslamers** [comment]
@dkns There has to be something wrong with the deb package. Switching the /usr/share/moosh/Moosh directory with the one from the master branch doesn't solve all problems though. The category export still runs with problems, but different ones:

```
<categories>
PHP Notice:  Undefined property: stdClass::$id in /usr/share/moosh/moosh_github/Moosh/Command/Moodle23/Category/CategoryExport.php on line 74

Notice: Undefined property: stdClass::$id in /usr/share/moosh/moosh_github/Moosh/Command/Moodle23/Category/CategoryExport.php on line 74
<category oldid='' PHP Notice:  Undefined property: stdClass::$idnumber in /usr/share/moosh/moosh_github/Moosh/Command/Moodle23/Category/CategoryExport.php on line 75

Notice: Undefined property: stdClass::$idnumber in /usr/share/moosh/moosh_github/Moosh/Command/Moodle23/Category/CategoryExport.php on line 75
PHP Notice:  Undefined property: stdClass::$name in /usr/share/moosh/moosh_github/Moosh/Command/Moodle23/Category/CategoryExport.php on line 82

Notice: Undefined property: stdClass::$name in /usr/share/moosh/moosh_github/Moosh/Command/Moodle23/Category/CategoryExport.php on line 82
name=''>
```

**Comment by tmuras** [comment]
This is caused by wrong category ID - you don't have category with ID 0, try
moosh category-export 1

(The check end proper error message should be there though).

**Comment by tmuras** [comment]
Please try latest master, moosh category-export 0 will now export all categories.
